@startuml

' Classes abstraites
abstract class Character {
  - type: String
  - name: String
  - lifePoints: int
  - damagePoint: int
  - offensiveEquipment: OffensiveEquipment
  - defensiveEquipment: DefensiveEquipment
  + getType(): String
  + setType(type: String): void
  + getName(): String
  + setName(name: String): void
  + getLifePoints(): int
  + setLifePoints(lifePoints: int): void
  + getDamagePoint(): int
  + setDamagePoint(damagePoint: int): void
  + getOffensiveEquipment(): OffensiveEquipment
  + setOffensiveEquipment(offensiveEquipment: OffensiveEquipment): void
  + getDefensiveEquipment(): DefensiveEquipment
  + setDefensiveEquipment(defensiveEquipment: DefensiveEquipment): void
  + toString(): String
}

abstract class OffensiveEquipment {
  - weaponType: String
  - weaponDamage: int
  - name: String
  + toString(): String
}

abstract class DefensiveEquipment {
  - defensiveType: String
  - name: String
  - defensivePoints: int
  + toString(): String
}

abstract class Cell {
  + interact(): String
  + toString(): String
}

' Classes concrètes
class Warrior {
  + Warrior(type: String, name: String)
  + toString(): String
}

class Wizard {
  + Wizard(type: String, name: String)
  + toString(): String
}

class Weapon {
  + toString(): String
}

class Spell {
  + toString(): String
}

class Shield {
  + toString(): String
}

class Potion {
  + toString(): String
}

class EmptyCell {
  + interact(): String
}

class EnemyCell {
  + interact(): String
}

class WeaponCell {
  + interact(): String
}

class PotionCell {
  + interact(): String
}

' Autres classes
class Board {
  - currentCase: int
  - MAX_CASE: int
  - cells: ArrayList<Cell>
  + initializeBoard(): void
  + getCurrentCase(): int
  + setCurrentCase(currentCase: int): void
  + getMaxCase(): int
  + getCurrentCell(): Cell
  + toString(): String
}

class Dice {
  + roll(): int
  + toString(): String
}

class Game {
  - playerPosition: int
  - board: Board
  - player: Character
  - gameStatus: String
  + mainMenu(): void
  + createCharacter(): void
  + playTurn(board: Board, dice: Dice): void
  + end(): void
  + start(): void
  + toString(): String
}

class Menu {
  + askPlayerString(textMessage: String): String
  + toString(): String
}

class OutOfBoardException {
  + OutOfBoardException(message: String)
}

' Relations d'héritage
Character <|-- Warrior
Character <|-- Wizard
OffensiveEquipment <|-- Weapon
OffensiveEquipment <|-- Spell
DefensiveEquipment <|-- Shield
DefensiveEquipment <|-- Potion
Cell <|-- EmptyCell
Cell <|-- EnemyCell
Cell <|-- WeaponCell
Cell <|-- PotionCell
Exception <|-- OutOfBoardException

' Relations d'association
Game --> Board
Game --> Dice
Game --> Menu
Game --> Character
Board o-- Cell
Character --> OffensiveEquipment
Character --> DefensiveEquipment

@enduml